### ISSUE TITLE
파비콘 안 불러와짐

### ISSUE THREAD

**Issue by bpforest** [jedeop/holssi#4]
![image](https://github.com/jedeop/holssi/assets/144601778/3f879444-9d3d-49bb-8921-8fe1e65d7042)

**Comment by jedeop** [comment]
https://github.com/jedeop/holssi-website/commit/73b9a642a01e80701a44f43013872c20a63724ad 를 통해 수정하였습니다.

추가로, 앞으로 홀씨 자체가 아닌 웹사이트 관련 이슈는 [웹사이트 Repo](https://github.com/jedeop/holssi-website)에 남겨주시길 부탁드립니다.

감사합니다.
