### ISSUE TITLE
글꼴 누락

### ISSUE THREAD

**Issue by bpforest** [jedeop/holssi#6]
글꼴이 안 불러와짐.
확인된 글꼴은 산돌 씨네마 극장체.
BES 적용 안 함

**Comment by jedeop** [comment]
현재 글상자의 글꼴이 로드되지 않는 것이 정상입니다.

글꼴은 라이선스 문제가 생길 수 있기 때문에 빌드 결과물에 포함하지 않고 있습니다. 추후 라이선스 문제를 해결할 방안이 생긴다면 글꼴도 로드되도록 개선하겠습니다.

감사합니다.
